import Vue from 'vue'
import 'vuetify/src/stylus/app.styl'
import {
  Vuetify,
  VApp,
  VNavigationDrawer,
  VFooter,
  VForm,
  VList,
  VBtn,
  VBtnToggle,
  VIcon,
  VGrid,
  VToolbar,
  VDivider,
  VMenu,
  VCard,
  VTabs,
  VTooltip,
  VSwitch,
  VCheckbox,
  VCombobox,
  VRadioGroup,
  VSelect,
  VTextField,
  VTextarea,
  VAlert,
  VDataTable,
  VPagination,
  VDatePicker,
  VDialog,
  VSnackbar,
  transitions,
  VChip,
  VAvatar,
  VProgressCircular,
  VProgressLinear,
  VSubheader
} from 'vuetify'
Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VFooter,
    VForm,
    VList,
    VBtn,
    VBtnToggle,
    VIcon,
    VGrid,
    VToolbar,
    VDivider,
    VMenu,
    VCard,
    VTabs,
    VTooltip,
    VSwitch,
    VCheckbox,
    VCombobox,
    VRadioGroup,
    VSelect,
    VTextField,
    VTextarea,
    VAlert,
    VDataTable,
    VPagination,
    VDatePicker,
    VDialog,
    VSnackbar,
    transitions,
    VChip,
    VAvatar,
    VProgressCircular,
    VProgressLinear,
    VSubheader
  },
  theme: {
    primary: '#1976D2',
    secondary: '#424242',
    default: '#757575',
    accent: '#82B1FF',
    error: '#dc3545',
    danger: '#cc2032',
    info: '#2196F3',
    success: '#28a745',
    warning: '#FFC107'
  },
})
